services:
  travel-todo-api:
    image: travel-todo-api:0.0.1-SNAPSHOT
    container_name: travel-todo-api-container
    ports:
      - "808:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
      - "RDS_ENDPOINT=jdbc:postgresql://db:5432/travel-todo-db"
      - "DB_USER=guest"
      - "DB_PASSWORD=hello_guest"
