services:
  travel-todo-api:
    image: travel-todo-api:0.0.1-SNAPSHOT
    container_name: travel-todo-api-container
    ports:
      - "808:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
      - "DB_ENDPOINT=db"
      - "DB_NAME=travel_todo_db"
      - "DB_USER=guest"
      - "DB_PASSWORD=hello_guest"
      - "GCP_CREDENTIALS_LOCATION=classpath:/certs/gc-service-account-key.json"
