spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_ENDPOINT}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      #   ddl-auto: update
      ddl-auto: none
    # properties:
    #   hibernate:
    # dialect: org.hibernate.dialect.PostgreSQLDialect
    # "[format_sql]": true
    show_sql: true
logging:
  level:
    # root: DEBUG
    org:
      hibernate:
        sql: DEBUG
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
server:
  port: 8443
  servlet:
    session:
      timeout: 4h
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:certs/keystore.p12
    key-store-password: changeit
    key-alias: springboot
app:
  cors:
    allowed-origins: https://localhost
# bucket4j:
#   filters:
#     - cache-name: create-reservation-from-text-api-call-quota-cache
#       url: ^/trip/[^/]+/reservation/analysis/text.*
#       filter-method: servlet
#       filter-order: 1
#       rate-limits:
#         - cache-key: "'TEST_KEY_STATIC'"
#           bandwidths:
#             - capacity: 2
#               time: 30
#               unit: days
#               refill-speed: interval
#   execute-predicates:
#     - METHOD=GET
#     - METHOD=POST
---
spring:
  config:
    activate:
      on-profile: local-init-data
  jpa:
    hibernate:
      ddl-auto: create
